#!/bin/sh

case $1 in
  "river")
    SPAWN_CMD='riverctl spawn'
    YAMBAR_CONFIG='~/.config/river/yambar.yml'
    ;;
  "sway")
    SPAWN_CMD='swaymsg exec'
    YAMBAR_CONFIG='~/.config/sway/yambar.yml'
    ;;
esac


~/scripts/loadgsettings


pgrep -x redshift || $SPAWN_CMD "redshift -l 45:9"
pgrep -f 'foot --server' || $SPAWN_CMD "foot --server"
pgrep -x mako || $SPAWN_CMD "mako"
pgrep -x xdg-desktop-portal || $SPAWN_CMD "/usr/lib/xdg-desktop-portal -r"
pgrep -x xdg-desktop-portal-wlr || $SPAWN_CMD "/usr/lib/xdg-desktop-portal-wlr" 

killall swaybg; $SPAWN_CMD 'swaybg -i ~/.config/wallpaper'
killall yambar; $SPAWN_CMD "yambar -c $YAMBAR_CONFIG"
