#!/bin/sh

# This is the example configuration file for river(1).
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the riverctl(1) man page for complete documentation

# Use the "logo" key as the primary modifier
mod="Mod4"
riverctl map normal $mod Return spawn "footclient"
riverctl map normal $mod P      spawn "rofi -show drun"
riverctl map normal $mod+Shift C close
riverctl map normal $mod+Shift Q exit

riverctl map normal $mod+Shift Return zoom
riverctl map normal $mod Space        toggle-float
riverctl map normal $mod F            toggle-fullscreen

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod       J focus-view next
riverctl map normal $mod       K focus-view previous
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous


# comma and period switch between displays
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous


# move
riverctl map normal $mod+Control H move left 100
riverctl map normal $mod+Control J move down 100
riverctl map normal $mod+Control K move up 100
riverctl map normal $mod+Control L move right 100

# resize
riverctl map normal $mod+Mod1 H resize horizontal -100
riverctl map normal $mod+Mod1 J resize vertical 100
riverctl map normal $mod+Mod1 K resize vertical -100
riverctl map normal $mod+Mod1 L resize horizontal 100

# mouse handling of windows
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal $mod $i               set-focused-tags    $tags
    riverctl map normal $mod+Shift $i         set-view-tags       $tags
    riverctl map normal $mod+Control $i       toggle-focused-tags $tags
    riverctl map normal $mod+Shift+Control $i toggle-view-tags    $tags
done

# focus all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0        set-focused-tags $all_tags

riverctl map normal $mod+Shift 0  set-view-tags $all_tags


# Layout
riverctl map normal $mod H mod-main-factor -0.05
riverctl map normal $mod L mod-main-factor +0.05

riverctl map normal $mod Up     layout rivertile top
riverctl map normal $mod Right  layout rivertile right
riverctl map normal $mod Down   layout rivertile bottom
riverctl map normal $mod Left   layout rivertile left
riverctl map normal $mod S      layout full

riverctl declare-mode passthrough
riverctl map normal $mod F11 enter-mode passthrough
riverctl map passthrough $mod F11 enter-mode normal

for mode in normal locked
do
    # Eject the optical drive
    riverctl map $mode None XF86Eject spawn eject -T

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn pamixer -i 5
    riverctl map $mode None XF86AudioLowerVolume  spawn pamixer -d 5
    riverctl map $mode None XF86AudioMute         spawn pamixer --toggle-mute

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn playerctl play-pause
    riverctl map $mode None XF86AudioPlay  spawn playerctl play-pause
    riverctl map $mode None XF86AudioPrev  spawn playerctl previous
    riverctl map $mode None XF86AudioNext  spawn playerctl next

    # Control screen backlight brighness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn light -A 5
    riverctl map $mode None XF86MonBrightnessDown spawn light -U 5
done

# Set repeat rate
riverctl set-repeat 30 300

# Set the layout on startup
riverctl layout rivertile left
riverctl outer-padding 2
riverctl view-padding 3

# Set app-ids of views which should float
riverctl float-filter-add "rofi"
riverctl float-filter-add "float"
riverctl float-filter-add "popup"

# Set app-ids of views which should use client side decorations
riverctl csd-filter-add "gedit"

# Set opacity and fade effect
# riverctl opacity 1.0 0.75 0.0 0.1 20

# keep alive a few processes

pgrep autostarter || nohup ~/scripts/autostarter &
